---
- name: Remove firewalld firewalls
  package: name={{item}} state=absent
  with_items:
    - firewalld
  when:
    - firewall_disable_firewalld

- name: Remove ufw firewalls
  package: name={{item}} state=absent
  with_items:
    - ufw
  when:
    - firewall_disable_ufw
